steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/crispy-system:$COMMIT_SHA
      - .

images:
  - gcr.io/$PROJECT_ID/crispy-system:$COMMIT_SHA

 # Deploy container image to Cloud Run
# - name: 'gcr.io/cloud-builders/gcloud'
#   args:
#   - 'run'
#   - 'deploy'
#   - '[SERVICE-NAME]'
#   - '--image'
#   - 'gcr.io/$PROJECT_ID/[SERVICE-NAME]:$COMMIT_SHA'
#   - '--region'
#   - '[REGION]'
