steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - gcr.io/$PROJECT_ID/crispy-system:$COMMIT_SHA
      - .

  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - crispy-system
      - --allow-unauthenticated
      - --image
      - gcr.io/$PROJECT_ID/crispy-system:$COMMIT_SHA
      - --region
      - asia-northeast1

images:
  - gcr.io/$PROJECT_ID/crispy-system:$COMMIT_SHA
