steps:
  - name: gcr.io/kaniko-project/executor:latest
    args:
      - --destination=gcr.io/$PROJECT_ID/crispy-system:$COMMIT_SHA
      - --cache=true
      - --cache-ttl=24h

  - name: gcr.io/cloud-builders/gcloud
    args:
      - run
      - deploy
      - crispy-system
      - --allow-unauthenticated
      - --image
      - gcr.io/$PROJECT_ID/crispy-system:$COMMIT_SHA
      - --region
      - asia-northeast1

images:
  - gcr.io/$PROJECT_ID/crispy-system:$COMMIT_SHA
